// swift-tools-version: 6.0

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "Juru",
    platforms: [
        .iOS("18.0")
    ],
    products: [
        .iOSApplication(
            name: "Juru",
            targets: ["AppModule"],
            bundleIdentifier: "com.antoniopaes.Juru",
            teamIdentifier: "9QV8HG6WSY",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .placeholder(icon: .smiley),
            accentColor: .presetColor(.pink),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            capabilities: [
                .camera(purposeString: "Juru uses the TrueDepth camera to detect facial muscle movements for speech synthesis. All tracking is processed locally on your device."),
                .motion(purposeString: "Used for head movement tracking stabilization.")
            ],
            appCategory: .medical
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: "."
        )
    ],
    swiftLanguageVersions: [.version("6")]
)