// swift-tools-version: 6.0

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "Juru",
    platforms: [
        .iOS("18.0")
    ],
    products: [
        .iOSApplication(
            name: "Juru",
            targets: ["AppModule"],
            bundleIdentifier: "com.antoniopaes.Juru",
            teamIdentifier: "9QV8HG6WSY",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .asset("AppIcon"),
            accentColor: .presetColor(.green),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .landscapeRight,
                .landscapeLeft
            ],
            capabilities: [
                .camera(purposeString: "Juru uses the TrueDepth camera to detect facial muscle movements for speech synthesis. All tracking is processed locally on your device."),
                .motion(purposeString: "Used for head movement tracking stabilization."),
                .faceID(purposeString: "We use Face ID to verify it's you and load your calibrated settings.")
            ],
            appCategory: .medical
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: ".",
            resources: [
                .process("Data/WordsData.json")
            ]
        )
    ],
    swiftLanguageModes: [.version("6")]
)
